[package]
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
name = "blis-sys"
version = "0.1.0"

[build-dependencies]
flate2 = "1.0.1"
git2 = "0.7"
reqwest = "0.8.5"
tar = "0.4.15"

[features]
default = ["cblas"]

cblas = []
static = []
system = []

[dependencies]
libc = "0.2.40"
