name: Rust

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  macos:
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        feature:
          - ""
          - static
          - system
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install BLIS by homebrew
      run: |
        brew install blis
      if: ${{ contains(matrix.feature, 'system') }}
    - uses: dtolnay/rust-toolchain@stable
    - run: >
        cargo test
        --features=${{ matrix.feature }}

  linux:
    runs-on: ubuntu-22.04
    container:
      image: rust
    strategy:
      fail-fast: false
      matrix:
        feature:
          - ""
          - static
          - system
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install BLIS by apt
      run: |
        apt update
        apt install -y libblis-dev
      if: ${{ contains(matrix.feature, 'system') }}
    - uses: dtolnay/rust-toolchain@stable
    - run: >
        cargo test
        --features=${{ matrix.feature }}
