name: Rust

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  macos:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        feature:
          - ""
          - static
          - system
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
    - name: Install BLIS by homebrew
      run: |
        brew install blis
      if: ${{ contains(matrix.feature, 'system') }}
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: >
          --features=${{ matrix.feature }}
          --manifest-path=blis-src/Cargo.toml

  linux:
    runs-on: ubuntu-20.04
    container:
      image: rust
    strategy:
      fail-fast: false
      matrix:
        feature:
          - ""
          - static
          - system
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: 'recursive'
    - name: Install BLIS by apt
      run: |
        apt update
        apt install -y libblis-dev
      if: ${{ contains(matrix.feature, 'system') }}
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: >
          --features=${{ matrix.feature }}
          --manifest-path=blis-src/Cargo.toml
